# Generated by Django 3.2.6 on 2021-08-07 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('required', models.BooleanField(blank=True, default=None, null=True)),
                ('user', models.ManyToManyField(related_name='volunteer_form', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
