# Generated by Django 3.2.6 on 2021-08-07 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alert_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_slot', models.TextField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_slots', to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_chooser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
