# Generated by Django 3.2.6 on 2021-08-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210811_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address1',
        ),
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, default='Address 2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='availability',
            field=models.TextField(blank=True, default='availability', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='City', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='preferred name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='intake_status',
            field=models.CharField(blank=True, default='volunteer status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='legal_name',
            field=models.CharField(blank=True, default='full legal name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_event',
            field=models.TextField(blank=True, default='preferred events', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, default='pronouns', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default='State', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, default='10-digit phone number', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(blank=True, default='permissions status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, default='Zipcode', max_length=10, null=True),
        ),
    ]
