# Generated by Django 3.2.6 on 2021-08-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210813_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='statusbar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteerslot',
            name='user',
        ),
    ]
