# Generated by Django 3.2.6 on 2021-08-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210813_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_header',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='doc_header',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_header',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statusbar',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerslot',
            name='vslot_text',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
