# Generated by Django 3.2.6 on 2021-08-16 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210815_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alert_creator', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ManyToManyField(related_name='document_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(related_name='event_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ManyToManyField(related_name='note_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statusbar',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers_status', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ManyToManyField(related_name='tag_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteerslot',
            name='user',
            field=models.ManyToManyField(related_name='event_volunteer', to=settings.AUTH_USER_MODEL),
        ),
    ]
