# Generated by Django 3.2.6 on 2021-08-17 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210816_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='event',
            field=models.ManyToManyField(related_name='announcementevent', to='core.Event'),
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ManyToManyField(related_name='alert_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statusbar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='volunteers_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
