# Generated by Django 3.2.6 on 2021-08-17 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210816_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='matched_event',
            field=models.ManyToManyField(blank=True, related_name='event_announcement', to='core.Event'),
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
