# Generated by Django 3.2.6 on 2021-08-18 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210817_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerslot',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, related_name='event_volunteer', to=settings.AUTH_USER_MODEL),
        ),
    ]
