# Generated by Django 3.2.6 on 2021-08-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_volunteerslot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='event',
            field=models.ManyToManyField(blank=True, default=None, related_name='announcementevent', to='core.Event'),
        ),
    ]
