# Generated by Django 3.2.6 on 2021-08-19 21:42

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_alert_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerslot',
            name='time',
        ),
        migrations.AddField(
            model_name='volunteerslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerslot',
            name='timespan',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
